# Generated by Django 4.2.10 on 2024-02-11 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingaccount',
            name='checking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='saving',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
