# Generated by Django 4.2.10 on 2024-02-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_checkingaccount_checking_savingaccount_saving'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkingaccount',
            old_name='checking',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='savingaccount',
            old_name='saving',
            new_name='user',
        ),
    ]
