# Generated by Django 4.2.10 on 2024-02-11 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_savingaccount_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='savingaccount',
            name='checking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_checking', to=settings.AUTH_USER_MODEL),
        ),
    ]
