# Generated by Django 4.2.10 on 2024-02-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_savingaccount_user_savingaccount_checking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingaccount',
            name='checking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_checking', to='account.checkingaccount'),
        ),
    ]
