# Generated by Django 4.2.10 on 2024-02-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saving',
        ),
    ]
